
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;

	private global::Gtk.Button btnShowMsg;

	private global::Gtk.Button btnLogin;

	private global::Gtk.Button btnNewDb;

	private global::Gtk.Entry etrPsw;

	private global::Gtk.Entry etrUser;

	private global::Gtk.Label label2;

	private global::Gtk.Label label1;

	private global::Gtk.Button button1;

	private global::Gtk.Button btnOsAbertas;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnShowMsg = new global::Gtk.Button();
		this.btnShowMsg.CanFocus = true;
		this.btnShowMsg.Name = "btnShowMsg";
		this.btnShowMsg.UseUnderline = true;
		this.btnShowMsg.Label = global::Mono.Unix.Catalog.GetString("ShowMessage");
		this.fixed1.Add(this.btnShowMsg);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnShowMsg]));
		w1.X = 10;
		w1.Y = 443;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnLogin = new global::Gtk.Button();
		this.btnLogin.CanFocus = true;
		this.btnLogin.Name = "btnLogin";
		this.btnLogin.UseUnderline = true;
		this.btnLogin.Label = global::Mono.Unix.Catalog.GetString("Login");
		this.fixed1.Add(this.btnLogin);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnLogin]));
		w2.X = 153;
		w2.Y = 436;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnNewDb = new global::Gtk.Button();
		this.btnNewDb.CanFocus = true;
		this.btnNewDb.Name = "btnNewDb";
		this.btnNewDb.UseUnderline = true;
		this.btnNewDb.Label = global::Mono.Unix.Catalog.GetString("New DB");
		this.fixed1.Add(this.btnNewDb);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnNewDb]));
		w3.X = 263;
		w3.Y = 434;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.etrPsw = new global::Gtk.Entry();
		this.etrPsw.CanFocus = true;
		this.etrPsw.Name = "etrPsw";
		this.etrPsw.IsEditable = true;
		this.etrPsw.InvisibleChar = '•';
		this.fixed1.Add(this.etrPsw);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.etrPsw]));
		w4.X = 202;
		w4.Y = 401;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.etrUser = new global::Gtk.Entry();
		this.etrUser.CanFocus = true;
		this.etrUser.Name = "etrUser";
		this.etrUser.IsEditable = true;
		this.etrUser.InvisibleChar = '•';
		this.fixed1.Add(this.etrUser);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.etrUser]));
		w5.X = 203;
		w5.Y = 363;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Senha:");
		this.fixed1.Add(this.label2);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label2]));
		w6.X = 19;
		w6.Y = 411;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Usuário:");
		this.fixed1.Add(this.label1);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label1]));
		w7.X = 17;
		w7.Y = 387;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.button1 = new global::Gtk.Button();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
		this.fixed1.Add(this.button1);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button1]));
		w8.X = 485;
		w8.Y = 441;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnOsAbertas = new global::Gtk.Button();
		this.btnOsAbertas.CanFocus = true;
		this.btnOsAbertas.Name = "btnOsAbertas";
		this.btnOsAbertas.UseUnderline = true;
		this.btnOsAbertas.Label = global::Mono.Unix.Catalog.GetString("O.S. Abertas");
		this.fixed1.Add(this.btnOsAbertas);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnOsAbertas]));
		w9.X = 2;
		w9.Y = 5;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 637;
		this.DefaultHeight = 493;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.btnShowMsg.Clicked += new global::System.EventHandler(this.OnBtnShowMsgClicked);
		this.btnNewDb.Clicked += new global::System.EventHandler(this.OnBtnNewDbClicked);
		this.button1.Clicked += new global::System.EventHandler(this.OnButton1Clicked);
		this.btnOsAbertas.Clicked += new global::System.EventHandler(this.OnBtnOsAbertasClicked);
	}
}
