
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;

	private global::Gtk.Label label1;

	private global::Gtk.Entry etrPsw;

	private global::Gtk.Label label2;

	private global::Gtk.Entry etrUser;

	private global::Gtk.Button btnShowMsg;

	private global::Gtk.Button btnLogin;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Usuário:");
		this.fixed1.Add(this.label1);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label1]));
		w1.X = 56;
		w1.Y = 74;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.etrPsw = new global::Gtk.Entry();
		this.etrPsw.CanFocus = true;
		this.etrPsw.Name = "etrPsw";
		this.etrPsw.IsEditable = true;
		this.etrPsw.InvisibleChar = '•';
		this.fixed1.Add(this.etrPsw);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.etrPsw]));
		w2.X = 123;
		w2.Y = 112;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Senha:");
		this.fixed1.Add(this.label2);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label2]));
		w3.X = 67;
		w3.Y = 117;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.etrUser = new global::Gtk.Entry();
		this.etrUser.CanFocus = true;
		this.etrUser.Name = "etrUser";
		this.etrUser.IsEditable = true;
		this.etrUser.InvisibleChar = '•';
		this.fixed1.Add(this.etrUser);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.etrUser]));
		w4.X = 122;
		w4.Y = 65;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnShowMsg = new global::Gtk.Button();
		this.btnShowMsg.CanFocus = true;
		this.btnShowMsg.Name = "btnShowMsg";
		this.btnShowMsg.UseUnderline = true;
		this.btnShowMsg.Label = global::Mono.Unix.Catalog.GetString("ShowMessage");
		this.fixed1.Add(this.btnShowMsg);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnShowMsg]));
		w5.X = 149;
		w5.Y = 244;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnLogin = new global::Gtk.Button();
		this.btnLogin.CanFocus = true;
		this.btnLogin.Name = "btnLogin";
		this.btnLogin.UseUnderline = true;
		this.btnLogin.Label = global::Mono.Unix.Catalog.GetString("Login");
		this.fixed1.Add(this.btnLogin);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnLogin]));
		w6.X = 158;
		w6.Y = 151;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.btnShowMsg.Clicked += new global::System.EventHandler(this.OnBtnShowMsgClicked);
		this.btnLogin.Clicked += new global::System.EventHandler(this.OnBtnLoginClicked);
	}
}
